/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BachcheRouteImport } from './routes/bachche'
import { Route as DarshanRouteImport } from './routes/darshan'
import { Route as KathayeinRouteImport } from './routes/kathayein'
import { Route as KhojRouteImport } from './routes/khoj'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrashnottariRouteImport } from './routes/prashnottari'
import { Route as PustakalayRouteImport } from './routes/pustakalay'
import { Route as SangrahRouteImport } from './routes/sangrah'
import { Route as ShravanRouteImport } from './routes/shravan'
import { Route as TirthankarRouteImport } from './routes/tirthankar'
import { Route as DarshanIndexRouteImport } from './routes/darshan.index'
import { Route as DarshanSlugRouteImport } from './routes/darshan.$slug'
import { Route as KathayeinIndexRouteImport } from './routes/kathayein.index'
import { Route as KathayeinSlugRouteImport } from './routes/kathayein.$slug'
import { Route as TirthankarIndexRouteImport } from './routes/tirthankar.index'
import { Route as TirthankarNRouteImport } from './routes/tirthankar.$n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BachcheRoute = BachcheRouteImport.update({
  id: '/bachche',
  path: '/bachche',
  getParentRoute: () => rootRouteImport,
} as any)
const DarshanRoute = DarshanRouteImport.update({
  id: '/darshan',
  path: '/darshan',
  getParentRoute: () => rootRouteImport,
} as any)
const KathayeinRoute = KathayeinRouteImport.update({
  id: '/kathayein',
  path: '/kathayein',
  getParentRoute: () => rootRouteImport,
} as any)
const KhojRoute = KhojRouteImport.update({
  id: '/khoj',
  path: '/khoj',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrashnottariRoute = PrashnottariRouteImport.update({
  id: '/prashnottari',
  path: '/prashnottari',
  getParentRoute: () => rootRouteImport,
} as any)
const PustakalayRoute = PustakalayRouteImport.update({
  id: '/pustakalay',
  path: '/pustakalay',
  getParentRoute: () => rootRouteImport,
} as any)
const SangrahRoute = SangrahRouteImport.update({
  id: '/sangrah',
  path: '/sangrah',
  getParentRoute: () => rootRouteImport,
} as any)
const ShravanRoute = ShravanRouteImport.update({
  id: '/shravan',
  path: '/shravan',
  getParentRoute: () => rootRouteImport,
} as any)
const TirthankarRoute = TirthankarRouteImport.update({
  id: '/tirthankar',
  path: '/tirthankar',
  getParentRoute: () => rootRouteImport,
} as any)
const DarshanIndexRoute = DarshanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DarshanRoute,
} as any)
const DarshanSlugRoute = DarshanSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DarshanRoute,
} as any)
const KathayeinIndexRoute = KathayeinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KathayeinRoute,
} as any)
const KathayeinSlugRoute = KathayeinSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KathayeinRoute,
} as any)
const TirthankarIndexRoute = TirthankarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TirthankarRoute,
} as any)
const TirthankarNRoute = TirthankarNRouteImport.update({
  id: '/$n',
  path: '/$n',
  getParentRoute: () => TirthankarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bachche': typeof BachcheRoute
  '/darshan': typeof DarshanRouteWithChildren
  '/kathayein': typeof KathayeinRouteWithChildren
  '/khoj': typeof KhojRoute
  '/login': typeof LoginRoute
  '/prashnottari': typeof PrashnottariRoute
  '/pustakalay': typeof PustakalayRoute
  '/sangrah': typeof SangrahRoute
  '/shravan': typeof ShravanRoute
  '/tirthankar': typeof TirthankarRouteWithChildren
  '/darshan/$slug': typeof DarshanSlugRoute
  '/kathayein/$slug': typeof KathayeinSlugRoute
  '/tirthankar/$n': typeof TirthankarNRoute
  '/darshan/': typeof DarshanIndexRoute
  '/kathayein/': typeof KathayeinIndexRoute
  '/tirthankar/': typeof TirthankarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bachche': typeof BachcheRoute
  '/khoj': typeof KhojRoute
  '/login': typeof LoginRoute
  '/prashnottari': typeof PrashnottariRoute
  '/pustakalay': typeof PustakalayRoute
  '/sangrah': typeof SangrahRoute
  '/shravan': typeof ShravanRoute
  '/darshan/$slug': typeof DarshanSlugRoute
  '/kathayein/$slug': typeof KathayeinSlugRoute
  '/tirthankar/$n': typeof TirthankarNRoute
  '/darshan': typeof DarshanIndexRoute
  '/kathayein': typeof KathayeinIndexRoute
  '/tirthankar': typeof TirthankarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bachche': typeof BachcheRoute
  '/darshan': typeof DarshanRouteWithChildren
  '/kathayein': typeof KathayeinRouteWithChildren
  '/khoj': typeof KhojRoute
  '/login': typeof LoginRoute
  '/prashnottari': typeof PrashnottariRoute
  '/pustakalay': typeof PustakalayRoute
  '/sangrah': typeof SangrahRoute
  '/shravan': typeof ShravanRoute
  '/tirthankar': typeof TirthankarRouteWithChildren
  '/darshan/$slug': typeof DarshanSlugRoute
  '/kathayein/$slug': typeof KathayeinSlugRoute
  '/tirthankar/$n': typeof TirthankarNRoute
  '/darshan/': typeof DarshanIndexRoute
  '/kathayein/': typeof KathayeinIndexRoute
  '/tirthankar/': typeof TirthankarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bachche'
    | '/darshan'
    | '/kathayein'
    | '/khoj'
    | '/login'
    | '/prashnottari'
    | '/pustakalay'
    | '/sangrah'
    | '/shravan'
    | '/tirthankar'
    | '/darshan/$slug'
    | '/kathayein/$slug'
    | '/tirthankar/$n'
    | '/darshan/'
    | '/kathayein/'
    | '/tirthankar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bachche'
    | '/khoj'
    | '/login'
    | '/prashnottari'
    | '/pustakalay'
    | '/sangrah'
    | '/shravan'
    | '/darshan/$slug'
    | '/kathayein/$slug'
    | '/tirthankar/$n'
    | '/darshan'
    | '/kathayein'
    | '/tirthankar'
  id:
    | '__root__'
    | '/'
    | '/bachche'
    | '/darshan'
    | '/kathayein'
    | '/khoj'
    | '/login'
    | '/prashnottari'
    | '/pustakalay'
    | '/sangrah'
    | '/shravan'
    | '/tirthankar'
    | '/darshan/$slug'
    | '/kathayein/$slug'
    | '/tirthankar/$n'
    | '/darshan/'
    | '/kathayein/'
    | '/tirthankar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BachcheRoute: typeof BachcheRoute
  DarshanRoute: typeof DarshanRouteWithChildren
  KathayeinRoute: typeof KathayeinRouteWithChildren
  KhojRoute: typeof KhojRoute
  LoginRoute: typeof LoginRoute
  PrashnottariRoute: typeof PrashnottariRoute
  PustakalayRoute: typeof PustakalayRoute
  SangrahRoute: typeof SangrahRoute
  ShravanRoute: typeof ShravanRoute
  TirthankarRoute: typeof TirthankarRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bachche': {
      id: '/bachche'
      path: '/bachche'
      fullPath: '/bachche'
      preLoaderRoute: typeof BachcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darshan': {
      id: '/darshan'
      path: '/darshan'
      fullPath: '/darshan'
      preLoaderRoute: typeof DarshanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kathayein': {
      id: '/kathayein'
      path: '/kathayein'
      fullPath: '/kathayein'
      preLoaderRoute: typeof KathayeinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoj': {
      id: '/khoj'
      path: '/khoj'
      fullPath: '/khoj'
      preLoaderRoute: typeof KhojRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prashnottari': {
      id: '/prashnottari'
      path: '/prashnottari'
      fullPath: '/prashnottari'
      preLoaderRoute: typeof PrashnottariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pustakalay': {
      id: '/pustakalay'
      path: '/pustakalay'
      fullPath: '/pustakalay'
      preLoaderRoute: typeof PustakalayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sangrah': {
      id: '/sangrah'
      path: '/sangrah'
      fullPath: '/sangrah'
      preLoaderRoute: typeof SangrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shravan': {
      id: '/shravan'
      path: '/shravan'
      fullPath: '/shravan'
      preLoaderRoute: typeof ShravanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tirthankar': {
      id: '/tirthankar'
      path: '/tirthankar'
      fullPath: '/tirthankar'
      preLoaderRoute: typeof TirthankarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/darshan/': {
      id: '/darshan/'
      path: '/'
      fullPath: '/darshan/'
      preLoaderRoute: typeof DarshanIndexRouteImport
      parentRoute: typeof DarshanRoute
    }
    '/darshan/$slug': {
      id: '/darshan/$slug'
      path: '/$slug'
      fullPath: '/darshan/$slug'
      preLoaderRoute: typeof DarshanSlugRouteImport
      parentRoute: typeof DarshanRoute
    }
    '/kathayein/': {
      id: '/kathayein/'
      path: '/'
      fullPath: '/kathayein/'
      preLoaderRoute: typeof KathayeinIndexRouteImport
      parentRoute: typeof KathayeinRoute
    }
    '/kathayein/$slug': {
      id: '/kathayein/$slug'
      path: '/$slug'
      fullPath: '/kathayein/$slug'
      preLoaderRoute: typeof KathayeinSlugRouteImport
      parentRoute: typeof KathayeinRoute
    }
    '/tirthankar/': {
      id: '/tirthankar/'
      path: '/'
      fullPath: '/tirthankar/'
      preLoaderRoute: typeof TirthankarIndexRouteImport
      parentRoute: typeof TirthankarRoute
    }
    '/tirthankar/$n': {
      id: '/tirthankar/$n'
      path: '/$n'
      fullPath: '/tirthankar/$n'
      preLoaderRoute: typeof TirthankarNRouteImport
      parentRoute: typeof TirthankarRoute
    }
  }
}

interface DarshanRouteChildren {
  DarshanSlugRoute: typeof DarshanSlugRoute
  DarshanIndexRoute: typeof DarshanIndexRoute
}

const DarshanRouteChildren: DarshanRouteChildren = {
  DarshanSlugRoute: DarshanSlugRoute,
  DarshanIndexRoute: DarshanIndexRoute,
}

const DarshanRouteWithChildren =
  DarshanRoute._addFileChildren(DarshanRouteChildren)

interface KathayeinRouteChildren {
  KathayeinSlugRoute: typeof KathayeinSlugRoute
  KathayeinIndexRoute: typeof KathayeinIndexRoute
}

const KathayeinRouteChildren: KathayeinRouteChildren = {
  KathayeinSlugRoute: KathayeinSlugRoute,
  KathayeinIndexRoute: KathayeinIndexRoute,
}

const KathayeinRouteWithChildren = KathayeinRoute._addFileChildren(
  KathayeinRouteChildren,
)

interface TirthankarRouteChildren {
  TirthankarNRoute: typeof TirthankarNRoute
  TirthankarIndexRoute: typeof TirthankarIndexRoute
}

const TirthankarRouteChildren: TirthankarRouteChildren = {
  TirthankarNRoute: TirthankarNRoute,
  TirthankarIndexRoute: TirthankarIndexRoute,
}

const TirthankarRouteWithChildren = TirthankarRoute._addFileChildren(
  TirthankarRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BachcheRoute: BachcheRoute,
  DarshanRoute: DarshanRouteWithChildren,
  KathayeinRoute: KathayeinRouteWithChildren,
  KhojRoute: KhojRoute,
  LoginRoute: LoginRoute,
  PrashnottariRoute: PrashnottariRoute,
  PustakalayRoute: PustakalayRoute,
  SangrahRoute: SangrahRoute,
  ShravanRoute: ShravanRoute,
  TirthankarRoute: TirthankarRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
